module.exports.en = {
    ERROR_GETCUSTOMER: 'error while get customer by field name: ',
    ERROR_ADDCUSTOMER: 'error while adding new customer: ',
    ERROR_GETLISTPRODUCT: 'error while get list product: ',
    ERROR_GETPRODUCTBYID: 'error while get product by productid: ',
    ERROR_GETTOKEN: "error while get Token by field name: ",
    ERRRO_ADDTOKEN: "error while adding new Token: ",

    // error user page
    ERROR_ADDUSER: 'error while adding new user: ',
    // error product.js
    ERROR_CREATEPRODUCT: 'error while creating product',
    ERROR_UPDATE_PRODUCT: ' error while updating product',
    // account.js
    ERROR_INCORRECT_ACCOUNT: 'Incorrect username or password',
    ERROR_UPDATE_PROFILE: 'There is something error while trying to update your profile',
    ERROR_NOT_CREATE_ACCOUNT: 'Can not registered account. Please check all input field to make sure data is right',
    ERROR_REGISTER_ACCOUNT: 'error while trying to register account ',
    ERROR_CUSTOMER_UPDATE_ACTIVE: 'error while update active in field customer: ',
    ERROR_EMAIL_NOTFOUND: 'The email address is not existed. Please try again.',
    ERROR_ACCOUNT_NOTACTIVE: 'Your account is not active. Please try again.',
    ERROR_TOKEN_EXPIRED: 'Your token is not expired. Please check your email or wait 2 hours to get new token',
    ERROR_SEND_MAIL: 'The email is not sent. Please check your email',
    ERROR_TOKEN_NOT_EXISTS: 'Your token is not existed. Please try again',
    ERROR_CHANGE_PASS: 'error while changing new password: ',
    ERROR_PASS_CONFIRM_INCORRECT: 'The password confirm is incorrect. Please try again',
    ERROR_PRODUCT_NOTFOUND: "Can not find this product",

    // error server
    ERROR_SV_RESET_PASS: 'error while trying to connect to reset password: ',
    ERROR_AUTHENTICATION: 'Authentication failed',
    ERROR_CANNOT_GET_VALUE: "Can not get value",
    ERROR_WALLET_NOT_EXISTS: "Wallet address exists",
    ERROR_CANNOT_CREATE_WALLET: "Can not create new wallet address",
    ERROR_CANNOT_REMOVE_WALLET: 'Can not remove this wallet!',
    ERROR_CANNOT_UPDATE_WALLET: 'Can not update this wallet!',
    ERROR_CANNOT_REMOVE_ORDER: 'Can not remove this order!',
    ERROR_CANNOT_GET_ORDER: 'Can not get this order!',
    ERROR_CANNOT_REMOVE_PRODUCT: 'Can not remove this product!',

    WARNING_ACCOUNT_NOT_ACTIVE: 'Your account is not active. Please active before login',
    WARNING_PASS_CHANGED: 'Your password is changed. Please login to enjoy!',
    WARNING_EMAIL_EXISTS: 'The email address is existed. Please try again',

    SUCCESS_CREATE_ACCOUNT: 'Your account is created successully. Please check email to active',

    LABEL_CHECKMAIL_TOKEN: 'Please check your email and find your token to reset your password',
    LABEL_ACCOUNT_ACTIVED: 'Your account is actived.',
    LABEL_PROFILE_UPDATED: 'Your profile is updated',
    LABEL_SUBJECT_VERIFY_ACCOUNT: '[myBitboxMining] Verify Account',
    LABEL_SUBJECT_RESET_PASS: '[myBitboxMining] Reset password',
    LABEL_HTML_VERIFY_ACCOUNT: '<p>Please click in this link to active your personal account <a href="{0}">Verify account</a></p>',
    LABEL_HTML_RESET_PASS: '<b>Hello! Please follow this link to reset your password: <a href="{0}">Reset password</a></b>',
    LABEL_DESC_BACK_DASHBOARD: 'Click to back dashboard page',
    LABEL_DESC_BACK_ORDER_DETAIL_PAGE: 'Please click here go to order detail page.',
    LABEL_DESC_BACK_ORDER_PAGE: 'Please click here go to my order page.',
    LABEL_DESC_BACK_REPORT_PAGE: 'Please click here go to report page.',
    LABEL_PAYMENT_SUCCESS: "You've successfully paid your order",
    LABEL_PAYMENT_NOT_PAID: "It looks like your bill has not been paid. Please contact your provider or leave requests for our check.",
    LABEL_PAYMENT_SAVE_ERROR: "We will check this issue. Maybe this is our fault.",
    LABEL_ORDER_NOTFOUND: "Can not find your order. Please check again",
    LABEL_ORDER_CANCEL: "You have canceled this invoice",
    LABEL_BUY_PRODUCT: "Buy {0} with price {1}",
    LABEL_BUY_PRODUCT_FAIL: 'Can not buy product. Please try again.',
    LABEL_CREATE_ORDER: "You have create an order with order id is {0}",
    LABEL_ORDER_APPROVE: "Your order with id {0} is approved!",
    LABEL_CREATE_PAYMENT: "You have successfully paid the order {0} with a payment code of {1}",
    LABEL_PRODUCTOFCUSTOMER_INSERT: 'Your product with id {0} has not been activated. Please click {1} choose a wallet address and active it.',
    LABEL_PRODUCT_INCLUDED_MAINTAINCE_FEE: 'Product is included maintaince fee',
    LABEL_PRODUCT_WITHOUT_MAINTAINCE_FEE: 'Product is not include maintaince fee',
    LABEL_MAINTENANCE_FEE: 'Maintenance Fee: ',
    LABEL_MAINTENANCE_FEE_PAID: "You have paid this month's maintenance fee of {0}",
    // web title
    TITLE_CUSTOMER_LOGIN: "Customer Login",
    TITLE_CUSTOMER_UPDATE_PROFILE: 'Customer profile',
    TITLE_CUSTOMER_REGISTER: 'Register account',
    TITLE_CUSTOMER_VERIFY_ACCOUNT: "Verify Account",
    TITLE_CUSTOMER_CHANGEPASS: "Customer Change Password",
    TITLE_CUSTOMER_CALCULATION: "Calculation",
    TITLE_CUSTOMER_DASHBOARD: 'Dashboard',
    TITLE_CUSTOMER_PROFILE: 'Customer profile',
    TITLE_CUSTOMER_ERROR_PAYMENT: 'Payment Error',
    TITLE_CUSTOMER_SUCCESS_PAYMENT: 'Payment Success',
    TITLE_CUSTOMER_ORDER_NOTFOUND: "Error order not found",
    TITLE_CUSTOMER_404: "Error 404",
    TITLE_CUSTOMER_CANCEL_ORDER: 'Cancel Order',
    TITLE_CUSTOMER_BUY_PRODUCT: 'Buy product',
    TITLE_CUSTOMER_WALLET: 'My wallet',
    TITLE_CUSTOMER_PRODUCT: 'My products',
    TITLE_CUSTOMER_ORDER: 'My order history',
    TITLE_CUSTOMER_HISTORY: 'My history',
    TITLE_CUSTOMER_PAYMENT_DETAIL: 'Payment detail',
    TITLE_CUSTOMER_ORDER_DETAIL: 'Order detail',
    TITLE_CUSTOMER_MAINTAINCE_FEE: 'Maintenance Fee',
    TITLE_AMOUNT_PAIR: 'Amount to be paid:',
    TITLE_PAYMENT_TERN: 'Payment tern:',
    TITLE_PAID_MAINTAIN_FEE: 'Payment of maintenance fee',
    TITLE_WITHDRAW_ETH: 'Withdraw ETH',

    // title
    TITLE_CHANGE_PASSWORD: 'Change password',
    TITLE_RESET_PASSWORD: 'Reset password',
    TITLE_REQUIRED: ' is required',
    TITLE_INPUT_PASSWORD: 'Password',
    TITLE_INPUT_CONFIRM_PASSWORD: 'Confirm password',
    TITLE_FORGOT_PASS: 'Forgot Password?',
    TITLE_FORGOT_PASS_DESC: 'You can reset your password here.',
    TITLE_MY_PRODUCT: 'My Product',
    TITLE_HERE: 'here',

    // react label
    RC_ID: 'ID',
    RC_NAME: 'Name',
    RC_EMAIL: 'Email',
    RC_FIRST_NAME: 'First name',
    RC_LAST_NAME: 'Last name',
    RC_WALLET_ADDRESS: 'Wallet address',
    RC_TOTAL_HASHRATE: 'Total hashrate',
    RC_TOTAL_BALANCE: 'Total balance',
    RC_ACTION: 'Action',
    RC_TABLE_WALLET: 'List wallet',
    RC_ADDWALLET: 'Add new wallet',
    RC_ADD_NEW_WALLET: 'Add new wallet address',
    RC_ERROR_CONFIRM_PASSWORD: 'Your confirm password is not match. Please try again',
    RC_EMAIL_RESET_PASS_REQUIRED: 'Email is required. Please input to reset your password',
    RC_HOUR : 'Hour',
    RC_DAY : 'Day',
    RC_WEEK : 'Week',
    RC_MONTH : 'Month',
    RC_YEAR : 'Year',
    RC_MY_TOTAL_HASH: 'My total hashing:',
    RC_MY_ESTIMATION: 'My Estimation',
    RC_PERIOD : 'Period (month)',
    RC_COIN: 'Coin (ETH)',
    RC_USD: 'USD',
    RC_ID: 'Id',
    RC_HASHRATE: 'Hashrate(Mh/s)',
    RC_ACTIVE: 'Active',
    RC_NOT_ACTIVE: 'Not active',
    RC_START_DATE: 'Start date',
    RC_END_DATE: 'End date',
    RC_REFRESH: 'Refresh',
    RC_ETH_PRICE: 'ETH price',
    RC_PRICE_COINMARKET: 'Price of Coinmarket',
    RC_GETMORE_HASHING: 'Get more hashing...',
    RC_ETH_VALUE: 'My ETH Value',
    RC_UNPAID_BALANCE : 'Unpaid Balance ETH',
    RC_LAST_24H: 'Last 24 Hours',
    RC_ADDON: 'Add on',
    RC_BUY: 'Buy',
    RC_PRICE: 'Price: ',
    RC_SALE_PRICE: 'Sale Price: ',
    RC_QUANTITY: 'Quantity',
    RC_DESCRIPTION: 'Description',
    RC_STATE: 'State',
    RC_AMOUNT: 'Amount',
    RC_CREATE_DATE: 'Create at',
    RC_ORDER_ID: 'Order ID',
    RC_CURRENCY: 'Currency',
    RC_BACK: 'Back',
    RC_PAYMENT_METHOD: 'Payment method',
    RC_PAYMENT_COUNTRY_CODE: 'Country code',
    RC_PAYMENT_USER_ID: 'Payer id',
    RC_PAYMENT_CART_NUMBER: 'Cart number',
    RC_MONTH: 'Month',
    RC_MONTHS: 'Months',
    RC_PERIOD_LABEL: 'Period: ',
    RC_OUR_SERVICES: 'Our services',

    // react label in customer product page
    RC_UPDATE_PRODUCT: 'Update Product',
    RC_MAINTENANCE_FEE: 'Maintenance fee (month)',

    // input placeholder
    WALLET_ADDRESS: 'Wallet address',
    WALLET_NAME: 'Wallet name',
    WALLET_DEFAULT_NAME_OPTION: 'Please choose your wallet to active product',
    UPDATE_NEW_WALLET_BALANCE: 'Your wallet balance is changed to {0} ETH',

    // button name
    BTN_SUBMIT: 'Submit',
    BTN_DETAILS: 'Detail',
    BTN_CLOSE: 'Close',

    // alert
    AL_TITLE_CONFIRM : 'Are you sure?',
    AL_TITLE_DESC : 'You want to delete {0}',
    AL_BTN_NO : 'No',
    AL_BTN_YES : 'Yes, Delete it!',
    AL_TITLE_EDIT_WALLET : 'Edit wallet',
    AL_BTN_CANCEL : 'Cancel',
    
    NOTE_MAINTAIN_FEE: 'If overdue but you still unpaid expenses. We will automatically convert into ETH under current rates and subtract directly from your balance.',
    MAINTAIN_FEE_STATUS: 'Status',
    MAINTAIN_PAID: 'Paid',
    MAINTAIN_NOT_PAID: 'Not paid',
    MAINTAIN_PAID_ETH: "Payment by eth",
    MAINTAIN_ETH: 'ETH',
}