export const FORGOT_PASSWORD = 'Forgot password'
export const LOG_IN = 'Log in'
export const REGISTER = 'Register'
export const CANCEL = 'Cancel'
export const SAVE = 'Save';
export const SEND = 'Send';
export const MY_WALLET = 'My Wallets';
export const WALLET_ID = 'Wallet ID:';
export const WALLET_NAME = 'Wallet name:';
export const ACTIVE_WORKERS = 'Active workers:';
export const UNPAID_BALANCE = 'Unpaid Balance:';
export const WALLET_BALANCE = 'Wallet Balance:';
export const MY_ACCOUNT = 'My Account';
export const CHANGE_PASSWORD = 'Change Password';
export const LOG_OUT = 'Log out';
export const PERIOUS = 'Perious';
export const HOUR = 'Hour';
export const DAY = 'Day';
export const WEEK = 'Week';
export const MONTH ='Month';
export const YEAR = 'Year';
export const ETH = 'ETH';
export const BTC = 'BTC';
export const USD = 'USD';
export const RELOAD = 'Reload';
export const DELETE_ALL = 'Delete all';
export const DISCONNECT = 'Disconnect';
export const TEMP = 'Temp(°C)';
export const FAN_SPEED = 'Fan(%)';
export const HASH_RATE = 'Hashrate';
export const TOTAL_HASH_RATE = 'Total hashrate(Mh/s): ';
export const GPU = 'GPU';
export const ADD_NEW_WALLET = 'Add new wallet ID';
export const EDIT_WALLET = 'Update wallet ID';
export const CREATE_ACCOUNT_LABEL='Create new account';
export const EDIT_YOUR_ACCOUNT='My account';
export const VALID_TOKEN_EMAIL = 'A valid email content token has been sent to you.\nPlease enter the token content to continue.';
export const MESSAGE_SHOW_QRCODE='Click camera icon to scan qrcode';