module.exports.en = {
    // user dashboard
    LABEL_CREATE_USER_TITLE: 'Create User',
    LABEL_CREATE_USER_SUCCESS_MESSAGE: 'User is created successfully!',
    LABEL_CREATE_USER_ERROR_MESSAGE: 'User is created fail!',
    LABEL_CREATE_USER_RESULT_TITLE: 'Create user result',
    LABEL_FORM_USERNAME: 'Username',
    LABEL_FORM_EMAIL: 'Email address',
    LABEL_FORM_FULLNAME: 'Full name',
    LABEL_FORM_PASSWORD: 'Password',
    LABEL_FORM_PASSWORD_CONFIRM: 'Confirm password',
    LABEL_FORM_PHONENUMBER: 'Phone number',
    LABEL_BUTTON_CREATE: 'Create',
    LABEL_BUTTON_BACK_TO_CREATE: 'Back to create login page to continue creating new user',
    LABEL_TEXT_IS_REQUIRED: 'is required',
    LABEL_LIST_USER: 'List User',
    LABEL_ADD_USER_BUTTON: '+ Add new user',
    LABEL_ID_TITLE: 'ID',
    LABEL_NAME_TITLE: 'Name',
    LABEL_EMAIL_TITLE: 'Email',
    LABEL_PHONE_TITLE: 'Phone',
    LABEL_ACTION_TITLE: 'Action',
    LABEL_ACTIVE_TITLE: 'Active',
    LABEL_START_DATE: 'Start date',
    LABEL_END_DATE: 'End date',
    LABEL_SKU: 'SKU',
    LABEL_HASHRATE: 'Hashrate',
    LABEL_USER_UPDATE: 'User update',
    LABEL_PRICE: 'Price',
    LABEL_SALE_PRICE: 'Sale price',
    LABEL_CURRENCY: 'Currency',
    LABEL_CURRENCY_SYMBOL: 'Symbol currency',
    LABEL_DESC_FIRST: 'Description 1',
    LABEL_DESC_SECOND: 'Description 2',
    LABEL_DESC_THIRD: 'Description 3',
    LABEL_PERIOD: 'Period',
    LABEL_STATE: 'State',
    LABEL_CHOOSE_LANGUAGE: 'Please choose language',
    LABEL_DEFAULT: 'Default',
    LABEL_APPLY: 'Apply',
    LABEL_UNACTIVE: 'Unactive',
    LABEL_BACK: 'BACK',
    // login
    LABEL_LOGIN_TITLE: 'Sign In',
    LABEL_EMAIL: 'Email',
    LABEL_PASSWORD: 'Password',
    LABEL_BUTTON_LOGIN: 'Login',
    LABEL_BUTTON_FORGOT_PASSWORD: 'Forgot password',

    // label product
    LABEL_MANAGE_PRODUCT: 'Manage product',
    LABEL_ADD_NEW_PRODUCT: 'Add new product',
    LABEL_ADD_OR_UPDATE_PRODUCT: 'Add or update product',
    LABEL_MAINTENANCE_FEE: 'Maintenance fee',
    // dashboard
    TITLE_CUSTOMER_DASHBOARD: 'User dashboard',
    TITLE_LIST_PRODUCT: 'List products',
    ERROR_PASSWORD_CONFIRM_MESSAGE: 'The password confirm is incorrect. Please try again',

    // error message from server
    ERROR_CREATE_USER_MESSAGE: 'Error while creating user',
    ERROR_GETUSER: 'Error while geting user',
    ERROR_AUTHENTICATION: 'Authentication failed',
    ERROR_GET_LIST_PRODUCT: 'Error while getting list of product',
    ERROR_NOT_FOUND_PRODUCT: 'There is no product been found',
    ERROR_CREATE_PRODUCT: 'Please input all valid data to create product',
    ERROR_UPDATE_PRODUCT: 'Error while updating product ',
    ERROR_CANNOT_UPDATE_PRODUCT: 'Can not update product. Please input valid data',
    ERROR_GET_LIST_LOCALE: 'Error while getting list of locale',
    ERROR_NOT_FOUND_LOCALE: 'There is no locale been found',
    ERROR_CREATE_PRICEBOOK: 'Error while creating price book',
    ERROR_EXISTING_SKU: 'The sku is existed. Please try to another sku',

    //login
    ERROR_INCORRECT_ACCOUNT: 'Incorrect email or password. Please try again',
    ERROR_ACCOUNT_NOT_ADMIN: 'You do not have permission to login',

}