export const ADD_LIST_WALLET = 'ADD_LIST_WALLET';
export const ADD_ITEM_WALLET_TO_LIST = 'ADD_ITEM_WALLET_TO_LIST';
export const UPDATE_ITEM_WALLET_TO_LIST = 'UPDATE_ITEM_WALLET_TO_LIST';
export const DELETE_ITEM_WALLET_FROM_LIST = 'DELETE_ITEM_WALLET_FROM_LIST';
export const ADD_LIST_PRODUCT = 'ADD_LIST_PRODUCT';
export const UPDATE_LIST_PRODUCT = 'UPDATE_LIST_PRODUCT';
export const DELETE_PRODUCT_FROM_LIST = 'DELETE_PRODUCT_FROM_LIST';
export const ADD_LIST_ORDER = 'ADD_LIST_ORDER';
export const ADD_PAYMENT_DETAIL = 'ADD_PAYMENT_DETAIL';
export const DELETE_ITEM_ORDER_FROM_LIST = 'DELETE_ITEM_ORDER_FROM_LIST';

