export const ADD_LIST_WALLET = 'ADD_LIST_WALLET';
export const ADD_ITEM_WALLET_TO_LIST = 'ADD_ITEM_WALLET_TO_LIST';
export const UPDATE_ITEM_WALLET_TO_LIST = 'UPDATE_ITEM_WALLET_TO_LIST';
export const DELETE_ITEM_WALLET_FROM_LIST = 'DELETE_ITEM_WALLET_FROM_LIST';
export const ADD_LIST_PRODUCT = 'ADD_LIST_PRODUCT';
export const UPDATE_LIST_PRODUCT = 'UPDATE_LIST_PRODUCT';

